package:
    name: physicalproperty
    # version: x.y.z
    # The version string is stored in `physicalproperty/version.py`.
    # `build.sh` includes code to properly incorporate the version
    # string in the built package.

source:
    path: ..

requirements:
    build:
        - python
        - numpy
        - astropy
    run:
        - python
        - numpy
        - astropy

test:
    requires:
        - nose

about:
    home: https://github.com/jrsmith3/physicalproperty
    license: MIT
    summary: Descriptor class for physical property attributes
